### PR TITLE
DM-19328: Investigate cause of small differences in Uber calibrations from w_2019_[06/10/14]

### PR DESCRIPTION
**Pull request by laurenam**

### CODE REVIEW

**Comment by TallJimbo** [comment]
I can imagine why the `fluxMag0` changes would be helpful now, while we're still trying to make sure using `PhotoCalib` doesn't change anything.  But in the very near future I hope we can rip all that out and just use a `PhotoCalib` directly to do all of our flux-magnitude conversions regardless of whether we're looking at `CalibrateTask`, `meas_mosaic`, or `jointcal` calibrations.

**Comment by laurenam** [comment]
I'm a tad puzzled by your comment as the point/need for this update was to move TO using the `PhotoCalib` to get the "instrumental flux at 0 magnitude" via `calexp.getPhotoCalib().getInstFluxAtZeroMagnitude()`.  Prior to this update, it was being retrieved from the "FLUXMAG0" card via `metadata.getScalar("FLUXMAG0")` (and I believe this card is no longer getting written to the calexp metadata).  Regardless, I think you are still in approval of this change?!

**Comment by TallJimbo** [comment]
Yes, still approved, and I do agree this is a better way to get a flux at magnitude zero.  I just don't understand why we actually need a flux at magnitude zero at all.

**Comment by laurenam** [comment]
Cool, thanks.  The magnitude zeropoint per CCD is the photometric calibration that comes out of SFM, so really I'm just applying the SFM calibration (oh, I guess you're saying I could've just used `calexp.getPhotoCalib().instFluxToNanojansky()`?  We can change that on the `pipe_analysis` refactor if you think it's preferred).

**Comment by TallJimbo** [comment]
Yup, that's exactly the sort of thing I had in mind, but I don't mind deferring it at all.

**Pull request merged**
